-- CreateEnum
CREATE TYPE "Category" AS ENUM ('TECHNOLOGY', 'MUSIC', 'GAMING', 'SPORTS', 'NEWS', 'ENTERTAINMENT', 'EDUCATION', 'TRAVEL', 'FOOD', 'FASHION', 'SCIENCE', 'ART', 'HEALTH', 'BUSINESS', 'COMEDY', 'MOVIES', 'BOOKS', 'PHOTOGRAPHY', 'FITNESS');

-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "category" "Category" NOT NULL DEFAULT 'COMEDY';
